eureka:
  instance:
    #实例ip 配置在sh中
    ip-address:
sync:
  cron:
    api:
      taggroup: 0 10 0 * * ?
      userbookexpire: 0 0 12 * * ?

verify:
  signName: 邻里爱读书
  smsTemplateCode: SMS_152506400

server:
  port: 20001

common:
  base:
    path: /home/microservice-uat