eureka:
  instance:
    #实例ip
    ip-address: 127.0.0.1
sync:
  cron:
    api:
      taggroup: 0 10 0 * * ?
      userbookexpire: 0 0 12 * * ?

verify:
  signName: 邻里爱读书
  smsTemplateCode: SMS_152506400
