eureka:
  instance:
    #实例ip 配置在sh中
    ip-address:
sync:
  cron:
    api:
      taggroup: 0 10 0 * * ?
      userbookexpire: 0 0 12 * * ?

verify:
  signName: 邻里爱读书
  smsTemplateCode: SMS_152506400

weixin:
  message:
    bookLendingReminderTemplateId: -LGNf9vuHBh7qksNK5PtommL9bjDkEYMsD6eiOIquPw
    bookLendingReminderTemplateUrl: http://upload.neighborbook.com.cn/order_detail.php?order=
    bookLendingStatusReminderTemplateId: RGHNpgGk5LwDLeGHh25iSuCNGdOm2fcoCl9-Wt_gLdA
    bookLendingStatusReminderTemplateUrl: http://upload.neighborbook.com.cn/order_detail.php?order=

server:
  port: 10001

common:
  base:
    path: /home/microservice