eureka:
  instance:
    #实例ip 配置在sh中
    ip-address:
sync:
  cron:
    api:
      taggroup: 0 10 0 * * ?
      userbookexpire: 0 0 12 * * ?

verify:
  signName: 邻里爱读书
  smsTemplateCode: SMS_152506400

weixin:
  message:
    bookLendingReminderTemplateId: isepgwj5MVQYN0gs8YrpLmxc2vUOWzuiv0LmcHU-OQg
    bookLendingReminderTemplateUrl: http://uat.neighborbook.com.cn/order_detail.php?order=
    bookLendingStatusReminderTemplateId: lkgelBLi1ZgC4nT-Sq2GsP3VypMseQrlROS-zrWT5n4
    bookLendingStatusReminderTemplateUrl: http://uat.neighborbook.com.cn/order_detail.php?order=

server:
  port: 20001

common:
  base:
    path: /home/microservice-uat