com:
  zjk:
    module:
      common:
        config:
          swagger2:
            api:
              url: https://github.com/NeighborBook/nb
              description: NeighborBook的微服务

common:
  authorization:
    application:
      name: nb-authorization
